name: 'Release helm chart'
description: 'Releases helm charts using semantic-release with the @swarm-io/release-config-helm release config. This action uses main and alpha branches and releases. This action deletes the alpha branch and re-creates it from main after a release from main'
inputs:
  token:
    description: github token to use for the release, if you want this to trigger other workflows such as flows on release created, pass in a PAT
    required: false
    default: ${{ github.token }}
  toggle-admins:
    description: 'If true, this action will disable the `include administrators` setting in branch protection for this branch, and re-enable it after release. Re-enabling is run using always()'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - uses: crazy-max/ghaction-dump-context@v1
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
    - uses: swarm-io/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true'
      with:
        token: ${{ inputs.token }}
        include-admins: false
    - id: semantic-release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extends: '@swarm-io/release-config-helm'
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
    - uses: swarm-io/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true' && always()  # Force to always run this step to ensure "include administrators" is always turned back on
      with:
        token: ${{ inputs.token }}
        include-admins: true
    - if: github.ref == 'main'
      name: Check alpha branch existence
      id: exists
      shell: bash
      run: |
        if git branch -r | grep -q 'origin/alpha$'
        then
        echo "alpha branch exists"
        echo "::set-output name=exists::true"
        else
        echo "alpha branch does not exist"
        echo "::set-output name=exists::false"
        fi
    - name: Delete alpha branch
      if: github.ref == 'main' && steps.exists.outputs.exists == 'true'
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ inputs.token }}
        branches: alpha
    - if: github.ref == 'main'
      name: Create new alpha branch
      shell: bash
      run: |
        git checkout -b alpha
    - if: github.ref == 'main'
      name: Push new alpha branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.token }}
        branch: alpha
